### ISSUE TITLE
Basic CLI

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#35]
## Description
As a user I want a basic command line interface so that I can run the mapper, build a new index, check or extend an existing index.
## Subtasks
- [x] Set up parameter parser.
- [x] Interface: mapper run.
- [x] Interface: index build.
- [x] Interface: index add.
- [x] Interface: index info.
- [x] Help interface in each subprogram.
- [x] Version information.
## Acceptance criteria
- [x] The user gets default help when mapper is run without arguments.
- [x] The user is able to start the mapper with index and input file. (throws 'not yet implemented' error)
- [x] The user is able to build a new index.
- [x] The user is able to get info from an existing index.
- [x] The user is able to add an neighbor annotation to an existing index.
- [x] The interface is intuitive enough so that the user does not require further help to use the mapper.
## Test procedures
Manual usage tests.
## Dependencies
- Depends on #37
