### ISSUE TITLE
Gzipped input support

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#36]
## Description
As a user I want to use the mapper directly with gzip-compressed files.
## Subtasks
- [ ] Find a gzip library (zlib.h is multi-platform).
- [ ] Write code to detect whether input file is gzipped.
- [ ] Update code to read input file using zlib functions.
- [ ] Embed the library in the software (no complicated installs!).
## Acceptance criteria
- [ ] The software distinguishes between compressed and plain files without extra parameters.
- [ ] A plain input file and its compressed version produce the exact same result.
- [ ] Installing/compiling the software does not require any additional step.
- [ ] The software supports the same platforms/OS as before.
## Test procedures
- [ ] Unit tests with compressed versions of the test example files.
