### ISSUE TITLE
Full stack error propagation

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#37]
## Description
Propagate errors in the code so that when the program crashes, the full stack of function calls is printed with a (optional) description message.
## Subtasks
- [ ] Define error macros.
- [ ] Unify `failure_return` tags.
- [ ] Update current code.
## Acceptance criteria
- [ ] All errors can be tracked.
- [ ] All internal calls between library functions have error check and propagation.
## Test procedures
It's difficult to unit test error propagation. A possibility is to check that the correct amount of lines (call stack) are written to `stderr`.
