### ISSUE TITLE
Improve code QA

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#38]
## Description
Improve code test coverage.
## Subtasks
- [x] Make new test files for memory tests.
- [x] Include `valgrind` check in test procedures.
- [x] Test all possible failure combinations for all functions.
  - [x] malloc call.
  - [x] null or incorrect arguments.
  - [x] file does not exist.
## Acceptance criteria
- [x] Improve code coverage.
- [x] No SIGSEGV when malloc fails.
## Test procedures
This is a test itself.
## Dependencies
- Depends on #37
