### ISSUE TITLE
Basic seeding and seed selection

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#39]
## Description
Basic algorithms to seed input sequences and select relevant seeds.
## Subtasks
- [ ] Define data structure for seeds.
- [ ] MEM seeding algorithm.
- [ ] Reseeding conditions.
- [ ] Algorithm to check seed neighbors.
- [ ] Define data structure to pass a list of seeds for alignment.
## Acceptance criteria
- [ ] MEM seeding.
- [ ] Seed neighbors.
## Test procedures
- [ ] Unit tests for all seeding and selection algorithms.
