### ISSUE TITLE
Basic sequence alignment

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#40]
## Description
Basic algorithms to align input sequences to a reference.
## Subtasks
- [ ] Define alignment scores.
- [ ] Implement basic NW alignment algorithm.
## Acceptance criteria
- [ ] Alignment score is reported.
- [ ] Report info such as number of insertions/deletions/matches/mismatches and their positions.
## Test procedures
- [ ] Unit tests with example sequences.
