### ISSUE TITLE
Breakpoint alignment algorithm

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#41]
## Description
As I user I want to be able to map multiple sequence fragments that do not necessarily span the full read.
## Subtasks
- [ ] Implement breakpoint algorithm.
## Acceptance criteria
- [ ] Sequence fragments are found with good breakpoint accuracy.
## Test procedures
- [ ] Unit tests to assess breakpoint detection accuracy.

# Algorithm description
