### ISSUE TITLE
Basic mapping quality score

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#42]
## Description
Mapping scores are assigned to determine the reliability of the mapping association.
## Subtasks
- [ ] Define basic mapping score taking into account:
  - [ ] Alignment scores of all aligned sequences.
  - [ ] Number of neighbors and distance to them.
## Acceptance criteria
- [ ] All reads must have a mapping quality score.
- [ ] Mapping scores must be inversely proportional to the mapping error probability.
## Test procedures
- [ ] Test with easy mappings and exact repeat sequences.
## Dependencies
- Depends on #40
