### ISSUE TITLE
Read input in stream/buffer mode

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#43]
## Description
As a user I want the mapper to read the input files in stream/buffer mode so that the memory used to store input data is limited.
## Subtasks
- [x] Define generic stack structure (stack.h).
- [x] Define sequence structure (seqread.h).
- [x] Create new lib file (io.h).
- [x] Define default buffer size.
- [x] Define i/o stream functions for several input formats.
- [x] Implement read/map loop in the main algorithm.
## Acceptance criteria
- [x] No sequences are truncated while reading.
- [x] Order is preserved in output file.
- [x] The buffer size is easy to modify.
## Test procedures
- [x] Unit tests with example input files.
- [x] Memory/file error tests.
## Dependencies
- Depends on #37
