### ISSUE TITLE
Output SAM format

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#44]
## Description
Make output compatible with SAM standard format.
## Subtasks
- [ ] Gather enough information at the print step to generate all SAM fields.
## Acceptance criteria
- [ ] Output follows all [SAM format specifications](https://samtools.github.io/hts-specs/SAMv1.pdf).
## Test procedures
- [ ] Generate input sequences to test all possible combinations of SAM flags.
