### ISSUE TITLE
Neighbor discovery algorihtm

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#45]
## Description
Use neighbor information on best alignment to find references to similar sequences and discover other unknown candidates.
## Subtasks
- [ ] Check neighbor information on best alignment(s).
- [ ] Use alignment info to generate seeds to similar loci.
- [ ] Filter out seeds to positions that have been already explored.
## Acceptance criteria
- [ ] Masked seeds should be discovered if alignment info is available on neighbor annotation.
## Test procedures
This is a difficult test...
