### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#46]
## Description
As a developer I want automated benchmarks to compare the performance with BWA, bowtie and any other mapper.
## Subtasks
TBD
## Acceptance criteria
- [ ] Comparison of performance in different reference genomes.
- [ ] Comparison of performance with simulated and real data.
- [ ] Benchmark the following performance indicators:
  - [ ] True positives per minute (sim).
  - [ ] Peak memory usage (sim/real).
  - [ ] Venn diagram of true positives (sim).
  - [ ] Venn diagram of sequences found (real).
  - [ ] Running time (real).
  - [ ] ROC curves (sim).
## Test procedures
None.
