### ISSUE TITLE
Add memory leak check to CI

### ISSUE THREAD

**Issue by ezorita** [ezorita/mapper#51]
## Description
As a developer I want an automated memory leak check.
## Subtasks
- [x] Update test/Makefile to run valgrind on the test cases.
- [x] Make sure that all functions are tested against memory leaks, both in success and failure.
- [x] Update .travis.yml if necessary, i.e. if `memtest` is not performed when `make test`.
## Acceptance criteria
- [x] All functions are tested against memory leaks.
- [x] Functions are forced to fail and no memory leaks are produced.
## Test procedures
- [x] Provoke memory leaks, e.g. do not free a variable during failure_return. (do not push!)
